# Generated by Django 2.2.7 on 2020-02-17 14:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonLandsatlist',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('productid', models.TextField(blank=True, db_column='productId', null=True)),
                ('entityid', models.TextField(blank=True, db_column='entityId', null=True)),
                ('acquisitiondate', models.TextField(blank=True, db_column='acquisitionDate', null=True)),
                ('cloudcover', models.FloatField(blank=True, db_column='cloudCover', null=True)),
                ('processinglevel', models.TextField(blank=True, db_column='processingLevel', null=True)),
                ('path', models.BigIntegerField(blank=True, null=True)),
                ('row', models.BigIntegerField(blank=True, null=True)),
                ('min_lat', models.FloatField(blank=True, null=True)),
                ('min_lon', models.FloatField(blank=True, null=True)),
                ('max_lat', models.FloatField(blank=True, null=True)),
                ('max_lon', models.FloatField(blank=True, null=True)),
                ('download_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amazon_landsatlist_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Landsat8',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.FloatField(blank=True, null=True)),
                ('perimeter', models.FloatField(blank=True, null=True)),
                ('pr_field', models.FloatField(blank=True, db_column='pr_', null=True)),
                ('pr_id', models.FloatField(blank=True, null=True)),
                ('rings_ok', models.FloatField(blank=True, null=True)),
                ('rings_nok', models.FloatField(blank=True, null=True)),
                ('path', models.FloatField(blank=True, null=True)),
                ('row', models.FloatField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=1, null=True)),
                ('sequence', models.FloatField(blank=True, null=True)),
                ('wrspr', models.CharField(blank=True, max_length=50, null=True)),
                ('pr', models.CharField(blank=True, max_length=50, null=True)),
                ('acqdayl7', models.CharField(blank=True, max_length=50, null=True)),
                ('acqdayl8', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'landsat8',
                'managed': False,
            },
        ),
    ]
